import Head from "next/head";
import About1 from "../components/about/About1";
import Banner1 from "../components/banner/Banner1";
import BestOffer1 from "../components/bestOffer/BestOffer1";
import RecentPost1 from "../components/blog/RecentPost1";
import Preloader from "../components/common/Prelaoder";
import Experties1 from "../components/cookingExperties/Experties1";
import Footer from "../components/footer/Footer";
import Gallery1 from "../components/gallary/Gallery1";
import Header from "../components/header/Header";
import Topbar from "../components/header/Topbar";
import  { Toaster } from 'react-hot-toast';


import MenuCards from "../components/menuCards/MenuCards";

function Home() {
  return (
    <>
      <Head>
        <title>Solara - Resturent Mangement</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/icon/logo.png" />
      </Head>
      {/* <Preloader /> */}
      {/* <Topbar /> */}
      <Header />
      <Banner1 />
      <MenuCards/>
      {/* <About1 /> */}
      {/* <NewItem1 />
      <PopularItem1 /> */}
      {/* <MenuList1 /> */}
      {/* <BestOffer1 /> */}
      {/* <Testimonial1 />
      <TesimonialVideo />
      <Experties1 />
      <Gallery1 />
      <RecentPost1 /> */}
      {/* <Footer /> */}
    </>
  );
}
export default Home;
