import Head from "next/head";
import React from "react";
import Footer from "../components/footer/Footer";
import Header from "../components/header/Header";
import { Toaster } from "react-hot-toast";

function Layout({ children , showFooter = true, isCustomHeader=false,  customHeaderClass,mobileViewClass}) {
  return (
    <div className={mobileViewClass}>
        <Toaster position="top-center"/>
    
      <Head>
        <title>Solara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/icon/logo.png" />
      </Head>
      <Header isCustomHeader={isCustomHeader} customHeaderClass={customHeaderClass} />
      {children}
     { showFooter == true ? <Footer /> :  null }
    </div>
  );
}

export default Layout;
